#!/bin/sh
#
# This file is in the public domain.
#
# For more information email LoranceStinson+csv@gmail.com.
# Or see http://lorance.freeshell.org/csvutils/

#**************************************************************************
# Defaults.
#**************************************************************************
CSV_ESCAPE=${CSV_ESCAPE:='"'}
CSV_SEPARATOR=${CSV_SEPARATOR:=","}
CSV_QUOTE=${CSV_QUOTE:='"'}
SKIP_ROWS="0"
FILE="-"
NL_TEXT=""
NUM_COLS=""
OUTPUT=""
SQL_ESCAPE='\'
SQL_QUOTE="'"
TAB_TEXT=""
TABLE_NAME="table"

#**************************************************************************
# usage() - Display the command line help text.
#**************************************************************************
usage(){
    if [ "$1" ] ; then
        echo "$1"
        echo ""
    fi
    cat<<EOHELP
Usage:  `basename $0` [OPTIONS] <FILE>
Converts a CSV file to an SQL file. Proper insert statements are generated.
Reads from STDIN by default.
Options:
    -a          Quote all fields, even numbers.
    -c          Create the table based on the first row. This implies -r 1.
    -C <COLS>   A comma separated list of columns to insert into.
    -e <ESCAPE> The CSV escape character. Defaults to $CSV_ESCAPE.
    -E <ESCAPE> The SQL escape character. Defaults to $SQL_ESCAPE.
    -h          This text.
    -N <TEXT>   Replace embedded newlines with TEXT. Defaults to a newline.
    -n <NUMBER> Output exactly NUMBER of columns. If a row has more columns
                the extra will be removed and if it has fewer extra blank
                columns will be added.
    -o <FILE>   Write the results to FILE.
    -q <QUOTE>  The CSV quote character. Defaults to $CSV_QUOTE.
    -Q <QUOTE>  The SQL quote character. Defaults to $SQL_QUOTE.
    -r <NUM>    Skip NUM rows of the CSV file or input.
    -s <SEP>    The CSV field separator. Defaults to $CSV_SEPARATOR.
    -T <TEXT>   Replaces tabs with TEXT. Defaults to a tab.
    -t <TABLE>  Table name for insert and create. Defaults to $TABLE_NAME.

Replacement for -N and -T are not checked for the SQL escape character.
EOHELP
    exit 1
}

#**************************************************************************
# Check and handle commandline options.
#**************************************************************************
while [ "$#" -gt 0 ] ; do
    case "$1" in
        # Quote numbers too.
        -a) QUOTE_NUMBERS="Y"; shift;;
        # Create a table.
        -c) CREATETABLE="Y"; shift;;
        # Columns to insert into.
        -C) [ "$2" ] && COLUMNS="$2"     || usage "$1 requires an argument."
            shift 2;;
        # CSV escape character.
        -e) [ "$2" ] && CSV_ESCAPE="$2"  || usage "$1 requires an argument."
            shift 2;;
        # SQL escape character.
        -E) [ "$2" ] && SQL_ESCAPE="$2"  || usage "$1 requires an argument."
            shift 2;;
        # Print the help text.
        -h) usage;;
        # Newline replacement text.
        -N) [ "$2" ] && NL_TEXT="$2"     || usage "$1 requires an argument."
            shift 2;;
        # The number of columns to output.
        -n) [ "$2" ] && NUM_COLS="$2"    || usage "$1 requires an argument."
            shift 2;;
        # Output to a file.
        -o) [ "$2" ] && OUTPUT="$2"      || usage "$1 requires an argument."
            shift 2;;
        # CSV quote character.
        -q) [ "$2" ] && CSV_QUOTE="$2"   || usage "$1 requires an argument."
            shift 2;;
        # SQL quote character.
        -Q) [ "$2" ] && SQL_QUOTE="$2"   || usage "$1 requires an argument."
            shift 2;;
        # Rows to skip
        -r) [ "$2" ] && SKIP_ROWS="$2"   || usage "$1 requires an argument."
            shift 2;;
        # CSV separator character.
        -s) [ "$2" ] && CSV_SEPARATOR="$2"     || usage "$1 requires an argument."
            shift 2;;
        # Tab replacement text.
        -T) [ "$2" ] && TAB_TEXT="$2"    || usage "$1 requires an argument."
            shift 2;;
        # Table name.
        -t) [ "$2" ] && TABLE_NAME="$2"  || usage "$1 requires an argument."
            shift 2;;
        # Mawk bug.
        -z) CSV_MAWK_BUG="Y"; shift;;
        # Strangely named files.
        --) [ "$2" ] && FILE="$2"; break;;
        # Read from STDIN.
        -)  FILE="-"; shift;;
        # Catch invalid options.
        -*) usage "Invalid option $1";;
        # Anything else should be a file.
        *)  FILE="$1"; shift;;
    esac
done

# Check the file.
[ "X$FILE" != "X-" -a ! -f "$FILE" -a ! -r "$FILE" ] &&
    usage "Unable to read the file ($FILE)."

# Send output to a file if requested.
if [ "$OUTPUT" ] ; then
    exec 1>$OUTPUT
fi

#**************************************************************************
# Perform the actual conversion.
# The heart is the function parse_csv I wrote for this purpose.
# See http://lorance.freeshell.org/csv/ for more information.
#**************************************************************************
awk -v columns="$COLUMNS" \
    -v csv_escape="$CSV_ESCAPE" \
    -v csv_quote="$CSV_QUOTE" \
    -v csv_sep="$CSV_SEPARATOR" \
    -v table="$TABLE_NAME" \
    -v create="$CREATETABLE" \
    -v skip="$SKIP_ROWS" \
    -v nltext="$NL_TEXT" \
    -v quote_numbers="$QUOTE_NUMBERS" \
    -v sql_escape="$SQL_ESCAPE" \
    -v sql_quote="$SQL_QUOTE" \
    -v tabtext="$TAB_TEXT" \
    -v numcols="$NUM_COLS" \
    -v csv_mawk_bug="$CSV_MAWK_BUG" \
'function parse_csv(string,csv,sep,quote,escape,newline,fields,instr,pos,strtrim) {
    # Make sure there is something to parse.
    if (length(string) == 0) return 0;
    string = sep string; # The code bellow always assumes ,FIELD.
    fields = 0; # The number of fields found thus far.
    while (length(string) > 0) {
        strtrim = 0; # Used to trim quotes off strings.
        # Handle a quoted field.
        if (substr(string,2,1) == quote) {
            instr = 1; pos = 2; strtrim = 1;
            do {
                pos++
                if (pos != length(string) &&
                    substr(string,pos,1) == escape &&
                    (substr(string,pos + 1,1) == quote ||
                     substr(string,pos + 1,1) == escape)) {
                    # Remove escaped quote characters.
                    string = substr(string,1,pos - 1) substr(string,pos + 1);
                } else if (substr(string,pos,1) == quote) {
                    # Found the end of the string.
                    instr = 0;
                } else if (newline && pos >= length(string)) {
                    # Handle embedded newlines if requested.
                    if (getline == -1) {
                        csverr = "Unable to read the next line.";
                        return -1;
                    }
                    string = string newline $0;
                }
            } while (pos < length(string) && instr)
            if (instr) {
                csverr = "Missing end quote.";
                return -1;
            }
        } else {
            # Handle an empty field.
            if (length(string) == 1 || substr(string,2,1) == sep) {
                csv[fields] = "";
                fields++;
                if (length(string) == 1)
                    return fields;
                string = substr(string,2);
                continue;
            }
            # Search for a separator.
            pos = index(substr(string,2),sep);
            # If there is no separator the rest of the string is a field.
            if (pos == 0) {
                csv[fields] = substr(string,2);
                fields++;
                return fields;
            }
        }
        if ((pos != length(string) && substr(string,pos + 1,1) != sep)) {
            csverr = "Missing separator.";
            return -1;
        }
        # Gather the field.
        csv[fields] = substr(string,2 + strtrim,pos - (1 + strtrim * 2));
        fields++;
        # Remove the field from the string for the next pass.
        string = substr(string,pos + 1);
    }
    return fields; }

BEGIN {
    if (sql_escape == "\\")
        escapere = "\\\\"
    else
        escapere = sql_escape
    if (columns) columns = "(" columns ") "
}
{   line++ # The current line number
    # Parse the line.
    fields = parse_csv($0,csv,csv_sep,csv_quote,csv_escape,"\n")
    # Check for errors.
    if (fields < 0 ) {
        print "ERROR: " csverr " at line # "line | "cat 1>&2"
        next
    }
    # Output the SQL to make the table it requested.
    if (create == "Y" && line == 1) {
        printf "create table %s (\n", table
        for (col = 0; col < fields; col++) {
            gsub(/ /,"_",csv[col])
            printf "	%s	text", csv[col]
            if (col < fields - 1) printf ","
            printf "\n"
        }
        printf ");\n"
        if (!numcols) numcols = fields
        next
    }
    # Skip rows if requested.
    if (line <= skip) next
    # Make sure the right number of columns are output.
    if (numcols){
        if (fields < numcols) {
            # Blank out the extra fields.
            for (col = fields; col < numcols; col++)
                csv[col] = ""
        }
        fields = numcols
    }
    # Build the insert statement.
    printf "insert into %s %svalues (", table, columns
    for (col = 0; col < fields; col++) {
        if (csv_mawk_bug && sql_escape == "\\")
            gsub (escapere,"\\\\\\",csv[col])
        else
            gsub (escapere,sql_escape sql_escape,csv[col])
        if (sql_escape != sql_quote)
            gsub (sql_quote,sql_escape sql_quote,csv[col])
        if (tabtext) gsub (/\t/,tabtext,csv[col])
        if (nltext) gsub (/\n/,nltext,csv[col])
        if (quote_numbers == "Y" || csv[col] !~ /^-*[0-9.][0-9.]*$/)
            printf "%s%s%s", sql_quote, csv[col], sql_quote
        else
            printf "%s", csv[col]
        if (col < fields - 1) printf ","
    }
    printf ");\n"
}' $FILE
